### PR TITLE
Error for emote menu

### PR DESCRIPTION
**Pull request by Dugojy69**
Hi i updated the emotes menu but im getting this error in F8. My server is based on vrp
Screenshot_12
.

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
Hi, perhaps use the correct fork of dpemotes and you won't have that issue.

**Comment by Dugojy69** [comment]
Sorry my english is bad and i dont understand what do you mean by "fork"

**Comment by AvaN0x** [comment]
> Sorry my english is bad and i dont understand what do you mean by "fork"

Get dpemotes from here https://github.com/TayMcKenzieNZ/dpemotes
Also the error you have is in the AnimationList.lua at line 2676

**Comment by Dugojy69** [comment]
> 

Yeah i removed my old dp emotes from my server and i added this one and im getting this error in F8 and i cannot open the menu at all :D

**Pull request closed without merging**
